use customer_shopping_behavior;
select * from customer limit 20;

-- Q1. What is the total revenue generated by male vs. female customers?

select gender, sum(purchase_amount) as revenue
from customer
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer);

-- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased, round(avg(review_rating), 2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type,
round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type;

-- Q5. Do subscribed customers spend more? 
-- Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount), 2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT
    `item_purchased` AS product,
    ROUND(
        SUM(CASE WHEN `discount_applied` = 'Yes' THEN 1 ELSE 0 END)
        / COUNT(*) * 100,
        2
    ) AS discount_purchase_percentage
FROM customer
GROUP BY `item_purchased`
ORDER BY discount_purchase_percentage DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

SELECT 
    CASE
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        WHEN previous_purchases > 10 THEN 'Loyal'
    END AS customer_segment,
    
    COUNT(*) AS customer_count

FROM customer

GROUP BY customer_segment

ORDER BY 
    CASE customer_segment
        WHEN 'New' THEN 1
        WHEN 'Returning' THEN 2
        WHEN 'Loyal' THEN 3
    END;

-- Q8. What are the top 3 most purchased products within each category?

SELECT 
    category,
    item_purchased,
    COUNT(*) AS purchase_count
FROM customer
GROUP BY category, item_purchased
ORDER BY category, purchase_count DESC;

-- OR

WITH product_sales AS (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS purchase_count
    FROM customer
    GROUP BY category, item_purchased
),

ranked_products AS (
    SELECT 
        category,
        item_purchased,
        purchase_count,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY purchase_count DESC
        ) AS product_rank
    FROM product_sales
)

SELECT 
    category,
    item_purchased,
    purchase_count,
    product_rank
FROM ranked_products
WHERE product_rank <= 3
ORDER BY category, product_rank;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT 
    CASE 
        WHEN previous_purchases > 5 THEN 'Repeat Buyer'
        ELSE 'Non-Repeat Buyer'
    END AS customer_type,

    COUNT(*) AS total_customers,

    SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END) AS subscribed_customers,

    ROUND(
        SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END) 
        / COUNT(*) * 100,
        2
    ) AS subscription_percentage

FROM customer

GROUP BY customer_type;

-- Q10. What is the revenue contribution of each age group

SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;